Update gocd-baby-all-day-err-damn-day.yml

diff --git a/.github/workflows/gocd-baby-all-day-err-damn-day.yml b/.github/workflows/gocd-baby-all-day-err-damn-day.yml
--- a/.github/workflows/gocd-baby-all-day-err-damn-day.yml
+++ b/.github/workflows/gocd-baby-all-day-err-damn-day.yml
@@ -23,7 +23,20 @@ jobs:
         cache: true
 
     - name: Build
-      run: go build -v ./...
+      run: |
+        go mod download
+        go install gotest.tools/gotestsum@latest
 
     - name: Test
-      run: go test -v ./...
+      run: |
+        go mod download
+        go install gotest.tools/gotestsum@latest
+        gotestsum --format=standard-verbose --junitfile=junit.xml
+    
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
